FROM debian:stretch
MAINTAINER DOOGLZ

# Libs for build Multi2Sim
RUN apt update --fix-missing &&  apt install -y wget unzip git build-essential automake autoconf libtool zlib1g-dev lib32gcc1 gcc-multilib libgtk-3-dev gdb && rm -rf /var/lib/apt 
# Get samplecode
ADD https://github.com/Multi2Sim/m2s-bench-amdsdk-2.5-src/archive/master.zip /bench/amd/
RUN unzip /bench/amd/master.zip /bench/amd/ && rm  /bench/amd/master.zip
## Build Multi2Sim with debug
RUN cd /tmp && git clone https://github.com/dooglz/multi2sim.git && cd multi2sim && libtoolize && aclocal && autoconf && automake --add-missing && ./configure --enable-debug && make -j 4 && make  -j 4 install 

